apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ingest.fullname" . }}-logstash-pipelines
data: 
  50-debug.conf: |
    # enables stdout for debugging
    output {
      stdout { codec => rubydebug }
    }  
{{- if .Values.logstashConfig.features.syslog.enabled }}
  01-syslog-input.conf: |
    input {
      tcp {
        port => 5144
        type => syslog
      }
      udp {
        port => 5144
        type => syslog
      }
    }
    
  51-syslog-output.conf: |    
    output {
      if [type] == "syslog" {
        elasticsearch {
          hosts => "data-service:9200"
          manage_template => false
          index => "syslog-%{+YYYY.MM.dd}"
          document_type => "%{[@metadata][type]}"
          codec => json
          #user => logstash_internal
          #password => changeme
        }
      }
    }
{{- end }}
{{- if .Values.logstashConfig.features.packetbeat.enabled }}
  02-packetbeat-input.conf: |
    input {
      redis {
        host => "ingest-service"
        key => "packetbeat"
        data_type => "list"
        tags => ["packetbeat"]
        codec => json
        batch_count => {{ .Values.logstashConfig.features.packetbeat.pipeline.batchCount }}
        threads => {{ .Values.logstashConfig.features.packetbeat.pipeline.threads }}
      }
    }
    
  52-packetbeat-output.conf: |
    output {
      if "packetbeat" in [tags] {
        elasticsearch {
          hosts => "data-service:9200"
          manage_template => false
          index => "packetbeat-%{+YYYY.MM.dd}"
          document_type => "event"
          codec => json
          #user => logstash_internal
          #password => changeme
        }
      }
    }
{{- end }}
{{- if .Values.logstashConfig.features.bro.enabled }}
  03-bro-input.conf: |
    input {
      redis {
        host => "ingest-service"
        key => "bro"
        data_type => "list"
        tags => ["bro"]
        codec => json
        batch_count => {{  .Values.logstashConfig.features.bro.pipeline.batchCount }}
        threads => {{  .Values.logstashConfig.features.bro.pipeline.threads }}
      }
    }
    
  53-bro-output.conf: |
    output {
      if "bro" in [tags] {
        elasticsearch {
          hosts => "data-service:9200"
          manage_template => false
          index => "bro-%{+YYYY.MM.dd}"
          document_type => "event"
          codec => json
          #user => logstash_internal
          #password => changeme
        }
      }
    }
{{- end }}
{{- if .Values.logstashConfig.features.suricata.enabled }}
  04-suricata-input.conf: |
    input {
      redis {
        host => "ingest-service"
        key => "suricata"
        data_type => "list"
        tags => ["suricata"]
        codec => json
        batch_count => {{  .Values.logstashConfig.features.suricata.pipeline.batchCount }}
        threads => {{  .Values.logstashConfig.features.suricata.pipeline.threads }}
      }
    }
    
  54-suricata-output.conf: |
    output {
      if "suricata" in [tags] {
        elasticsearch {
          hosts => "data-service:9200"
          manage_template => false
          index => "suricata-%{+YYYY.MM.dd}"
          document_type => "event"
          codec => json
          #user => logstash_internal
          #password => changeme
        }
      }
    }
{{- end }}
{{- if .Values.logstashConfig.features.winlogbeat.enabled }}
  05-winlogbeat-input.conf: |
    input {
      redis {
        host => "ingest-service"
        key => "winlogbeat"
        data_type => "list"
        tags => ["winlogbeat"]
        codec => json
        batch_count => {{ .Values.logstashConfig.features.winlogbeat.pipeline.batchCount }}
        threads => {{ .Values.logstashConfig.features.winlogbeat.pipeline.threads }}
      }
    }
  06-winlogbeat-helk-attack-input.conf: |
    input {
      file
      {
        path => "/usr/share/logstash/cti/mitre_attack.csv"
        start_position => "beginning"
        sincedb_path => "/dev/null"
        tags => [ "attack" ]
      }
    }
  55-winlogbeat-helk-sysmon-output.conf: |
    # https://github.com/Cyb3rWard0g/HELK/tree/master/helk-logstash/pipeline

    output {
      if [log_name] == "Microsoft-Windows-Sysmon/Operational"{
        elasticsearch {
          hosts => ["data-service:9200"]
          index => "winlogbeat-endpoint-winevent-sysmon-%{+YYYY.MM.dd}"
          template => "/usr/share/logstash/output_templates/winevent-sysmon-template.json"
          template_name => "winlogbeat-endpoint-winevent-sysmon"
          template_overwrite => true
          document_id => "%{[@metadata][log_hash]}"
        }
      }
    }
    
  56-winlogbeat-helk-winevent-security-output.conf: |
    # https://github.com/Cyb3rWard0g/HELK/tree/master/helk-logstash/pipeline

    output {
      # Added tags in if statement
      if [log_name] == "Security" and "winlogbeat" in [tags] {
        elasticsearch {
          hosts => ["data-service:9200"]
          index => "winlogbeat-endpoint-winevent-security-%{+YYYY.MM.dd}"
          template => "/usr/share/logstash/output_templates/winevent-security-template.json"
          template_name => "winlogbeat-endpoint-winevent-security"
          template_overwrite => true
          document_id => "%{[@metadata][log_hash]}"
        }
      }
    }

  57-winlogbeat-helk-winevent-system-output.conf: |
    # https://github.com/Cyb3rWard0g/HELK/tree/master/helk-logstash/pipeline

    output {
      if [log_name] == "System" and "winlogbeat" in [tags] {
        elasticsearch {
          hosts => ["data-service:9200"]
          index => "winlogbeat-endpoint-winevent-system-%{+YYYY.MM.dd}"
          template => "/usr/share/logstash/output_templates/winevent-system-template.json"
          template_name => "winlogbeat-endpoint-winevent-system"
          template_overwrite => true
          document_id => "%{[@metadata][log_hash]}"
        }
      }
    }
  
  58-winlogbeat-helk-winevent-application-output.conf: |
    # https://github.com/Cyb3rWard0g/HELK/tree/master/helk-logstash/pipeline

    output {
      if [log_name] == "Application" and "winlogbeat" in [tags] {
        elasticsearch {
          hosts => ["data-service:9200"]
          index => "winlogbeat-endpoint-winevent-application-%{+YYYY.MM.dd}"
          template => "/usr/share/logstash/output_templates/winevent-application-template.json"
          template_name => "winlogbeat-endpoint-winevent-application"
          template_overwrite => true
          document_id => "%{[@metadata][log_hash]}"
        }
      }
    }
    
  59-winlogbeat-helk-winevent-powershell-output.conf: |
    # https://github.com/Cyb3rWard0g/HELK/tree/master/helk-logstash/pipeline

    output {
      if [source_name] == "Microsoft-Windows-PowerShell" or [source_name] == "PowerShell"{
        elasticsearch {
          hosts => ["data-service:9200"]
          manage_template => false
          index => "winlogbeat-endpoint-winevent-powershell-%{+YYYY.MM.dd}"
          document_id => "%{[@metadata][log_hash]}"
        }
      }
    }
    
  60-winlogbeat-helk-winevent-wmiactivity-output.conf: |
    # https://github.com/Cyb3rWard0g/HELK/tree/master/helk-logstash/pipeline

    output {
      if [log_name] == "Microsoft-Windows-WMI-Activity/Operational"{
        elasticsearch {
          hosts => ["data-service:9200"]
          index => "winlogbeat-endpoint-winevent-wmiactivity-%{+YYYY.MM.dd}"
          template => "/usr/share/logstash/output_templates/winevent-wmiactivity-template.json"
          template_name => "winlogbeat-endpoint-winevent-wmiactivity"
          template_overwrite => true
          document_id => "%{[@metadata][log_hash]}"
        }
      }
    }
    
  61-winlogbeat-helk-attack-output.conf: |
    # https://github.com/Cyb3rWard0g/HELK/tree/master/helk-logstash/pipeline

    output {
      if "attack" in [tags]{
        elasticsearch {
            hosts => ["data-service:9200"]
            index => "mitre-attack-%{+YYYY.MM.dd}"
        }
      }
    }
{{- end }}
